apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:RlHjT8KO9k2a02tbyD66rBVTKxfYztwoVrI=,iv:DWNq7zQQ3pZm/1XfrPj4K5R87Z1smEoGoAm/yAYNJbY=,tag:PIcMPd95muV0oBSuUB+DdQ==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:t+aP3zKquqAipq9XD3ABkPi/FiV3otjBnl9YzwwUz4H742aIHA==,iv:8zVi50hIjEoKcDGMIWpEtW0Rbp/sVPjNppEO0OwKFOc=,tag:XbDWIDWA3CcuG64AN4TUDQ==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:JFCUVsElbUcIXX67/jIE1g==,iv:SH22rKAZHUklf1cZ/5p8BfagY8YeWsh2mllgqUPkUt4=,tag:QFb1Wed6tLhyWwSAtco9Bg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-04-18T11:14:48Z"
    mac: ENC[AES256_GCM,data:Zpq1CVtDm5b6XgOXmaa437Ne3bv9h8YpkNGjzKWonHoJlxUu9K5blnvDW/zVqTK4aV/52Gjxf4Iw7z8QWo9OqJHPAg5+XElZQWMaIKJVrgzwz3cHxGCqFDZ/bnQRl2RpUFCpNfG/WkpO/5AHZRk3/khhkNEFeIa+9rBd6yOdLcI=,iv:nOhxiY9nyxnjV8stTESCQr2ox6JdjuMFLJ0y82WY7/A=,tag:LIE6NKxxBstbvUktf2Lj/w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
