apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:83lCfjFUSMsMRqj6WlM70EG8ER1XrjhVwWmnH11u5a7tVHFcC+BDuw==,iv:UX2NSYFLuzjf7+mbnorSsL/mKNeDllau/QMMZ3tadrM=,tag:ny2noKgk1KzeBXI9c5iC4Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-04-18T11:14:48Z"
    mac: ENC[AES256_GCM,data:8OFZkIdAiRctinSDBOPBDpJ8TOYMk2vEimO+mZOc7+llQcoyALuT515KixqTXeklDBjN2dom+gPXJjQDY19La6Pkt53zPoAO21ZJMILPOP5ZWj20Ii3fVTT3NNd7LERcMnkklIh2oeqCiGB/PvWUzNPM/hv+lr5wA9sGp5dCo/U=,iv:ngCrWiRvfivRWyLGa6QxMonnY4SCmom4+0+Cm0EH8fw=,tag:5T7YQQGQ7PihFB2JcaaYcw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
