apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:5wM+ln5k59BwIZ/lL7GzhxE2ZaUwhzvZdwYmGh9tTMZzc+9kEw==,iv:65IkINeV8g13c0KEwAB+hKUxFedEFYcbINFPOxjn7sE=,tag:sZJSXKwvlDjIYoZL0BjXHg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-04-18T11:14:48Z"
    mac: ENC[AES256_GCM,data:SFy2RWoTRKmDfq0q0McovE57vnSqp1fKvhHQmnNYnLMDCn/FaUTpneP7nDkVASZbA7QSZsp3hj6Nr3sLFNOGPe9U/NAOdLVs4Srv+IDMv9vaVJYbM2GKAPHuIrXS02u+cG/o0PRzxQBW0cocOw44PIk2AViOfb92OWUZ+FYsuvM=,iv:mRr4joeithPlWhyYxLKLUAjqZ5GSeNDX2/6/mgbW47g=,tag:AbOXtBc7f9n12SlvgJEauA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
