apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:ZNY6xlJ8ZCGenO9bp/CVJEEGhdySPoSBpaM=,iv:L9d5q0j4ONdqLcheDK3XHO/qEkeJMiYcRf0LHjgWLcs=,tag:a0HXnTGTV3qq9F+7zfsXog==,type:str]
    api-key: ENC[AES256_GCM,data:uaBrDXXr66+IeZrsXSgt8WDaZE7x3XQKreuI9BW2rzuQm8roGg==,iv:HREOc8fIL1ZfcSxAYwbDup5DrJIzPTBzuNrYB+yxeRk=,tag:YhVaGdw0glqOWEc3hkXJoA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-04-18T11:14:48Z"
    mac: ENC[AES256_GCM,data:qSMstDWPLe2DT6h5HOR11sm6hIAn2sOVfd8v7ZKjIQV3rLZLNOZqwlpsabwioBCogsPY+2eqVxyJZyLyoWmB/CqensBwnqKyOgX+nhwTXmR6aVUBT6UiQUal1N+IaZifwJGMyMy7S5ZZAYeN81WPfeGaKIfrimvMf0zzJYQiqRo=,iv:Usn9/loDK4vfPeP0/EbgsknoZ5t7Q9fhIS2En0qqrKM=,tag:MM5qQoH/dxQjkgJTkDz0qw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
