apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:QE8TRlaTBWKEDW0zE6dz4ZDAR4jVW3TZ5vOhPbk8amSLZJoi/borrYpQroS0tj60rn+VJH3Ynt/SGruc,iv:cR4ZFBJpGS1nfRWIoA3MdsuQTUpCXmKNMsCmZFeomKs=,tag:CO04vRITJpZ+Hfpj6KnOyg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-04-18T11:14:49Z"
    mac: ENC[AES256_GCM,data:Lhz5atVQHHFfSfj4dXZi1fyI88dx1JCj4z7YJV8A2zeD+YMtx7xxvI8+M2W3AGz76SryGaUydBS87ZKOHQry6dve7LKmnNeKDBN1qtfqrAnbDTzCa0pb1ZMfPTvxeHlThwyb/dsqpJ11k49ZEAQNtLo9JNAGInSVvMwohuEGWFw=,iv:ZziZtWGK5QomRV3GshM4/du/2wzVRWz7HHE2YJNQ32o=,tag:d4Jx0LeNFb9yMEZC8Mwekg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
