apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:ED3fqEHVbU1B1jY=,iv:NkfJpG2YXWH/Nmz/SwjvxhoEQhDjqUQPiwxefgkAXKU=,tag:IQFfGWvlG0cvD3pl9VfrRg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:MBYLbRZHjrhsDlAOHd2MBGs1if6EMCzO12s=,iv:V9iJ/05u/dd2FMOfq93yefzo50avxw25ya8OxFs4ZW4=,tag:vipW/uPCqi226FAolySKAg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-04-18T11:14:48Z"
    mac: ENC[AES256_GCM,data:TFUKfyGGTs74sNR9DbNFnogQuw4su/CxWX0oeDrizxl3wBT8mNZNhFnj6Eo6JBst12475NdDpSFVYqy7cDqlj4/Pv3ENepbN8Ai88KYab88+No3mqjrnD+tyxXE4k4icyMNn9NTzromoesrMF6PA5IsBZXbKUOl24IK+BLxPu1A=,iv:a8N7iEK2lDQC1NVWcqJfHeOOQgQApFY3bCrS/m7FIRM=,tag:5mZRQbeUC2EMGWUJphMtwA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
